from confapp import conf

conf.PYFORMS_JSFILES_DEBUG += [
    "ControlCalendar.js",
    "ControlCodeMirror.js",
    "ControlHButtons.js",
    "ControlDir.js",
    "ControlDrawInImg.js",
    "ControlFeed.js",
    "ControlHighlightText.js",
    "ControlImgViewer.js",
    "ControlMap.js",
    "ControlMenu.js",
    "ControlOrganogram.js",
    "ControlPlayer.js",
    "ControlPlayerJs.js",
    "ControlQueryCards.js",
    "ControlSearch.js",
    "ControlThumbnailSelection.js",
    "ControlTimeout.js",
    "ControlTree.js",
    "ControlVisVis.js",
    "ControlWorkflow.js",
    "ControlChartJsLine.js",
]

conf.CSSFILES += [
    "/static/jquery.flowchart/jquery.flowchart.min.css",
    "/static/treant/Treant.css",
    "/static/codemirror/codemirror.css",
    "/static/zoomist/zoomist.min.css",
    "/static/leaflet/leaflet.css",
    "/static/leaflet/draw/leaflet.draw.css",
]

conf.JSFILES += [
    "/static/chart.js/Chart.min.js",
    "/static/jquery.flowchart/jquery.panzoom.min.js",
    "/static/jquery.flowchart/jquery.mousewheel.min.js",
    "/static/jquery.flowchart/jquery.flowchart.min.js",
    "/static/treant/Treant.js",
    "/static/canvas-video-player.js",
    "/static/codemirror/codemirror.js",
    "/static/codemirror/xml.js",
    "/static/codemirror/css.js",
    "/static/codemirror/javascript.js",
    "/static/codemirror/htmlmixed.js",
    "/static/codemirror/autorefresh.js",
    '/static/TextHighlighter.min.js',
    "/static/zoomist/zoomist.min.js",

    "/static/leaflet/leaflet.js",
    "/static/leaflet/draw/Leaflet.draw.js",
    "/static/leaflet/draw/Leaflet.Draw.Event.js",
    "/static/leaflet/draw/Toolbar.js",
    "/static/leaflet/draw/Tooltip.js",
    "/static/leaflet/draw/ext/GeometryUtil.js",
    "/static/leaflet/draw/ext/LatLngUtil.js",
    "/static/leaflet/draw/ext/LineUtil.Intersect.js",
    "/static/leaflet/draw/ext/Polygon.Intersect.js",
    "/static/leaflet/draw/ext/Polyline.Intersect.js",
    "/static/leaflet/draw/ext/TouchEvents.js",
    "/static/leaflet/draw/draw/DrawToolbar.js",
    "/static/leaflet/draw/draw/handler/Draw.Feature.js",
    "/static/leaflet/draw/draw/handler/Draw.SimpleShape.js",
    "/static/leaflet/draw/draw/handler/Draw.Polyline.js",
    "/static/leaflet/draw/draw/handler/Draw.Marker.js",
    "/static/leaflet/draw/draw/handler/Draw.Circle.js",
    "/static/leaflet/draw/draw/handler/Draw.CircleMarker.js",
    "/static/leaflet/draw/draw/handler/Draw.Polygon.js",
    "/static/leaflet/draw/draw/handler/Draw.Rectangle.js",
    "/static/leaflet/draw/edit/EditToolbar.js",
    "/static/leaflet/draw/edit/handler/EditToolbar.Edit.js",
    "/static/leaflet/draw/edit/handler/EditToolbar.Delete.js",
    "/static/leaflet/draw/Control.Draw.js",
    "/static/leaflet/draw/edit/handler/Edit.Poly.js",
    "/static/leaflet/draw/edit/handler/Edit.SimpleShape.js",
    "/static/leaflet/draw/edit/handler/Edit.Rectangle.js",
    "/static/leaflet/draw/edit/handler/Edit.Marker.js",
    "/static/leaflet/draw/edit/handler/Edit.CircleMarker.js",
    "/static/leaflet/draw/edit/handler/Edit.Circle.js",
]
